- name: Download Golang binaries
  ansible.builtin.shell: GO111MODULE=on GOBIN=/usr/local/bin go install -v {{ item }}
  loop: "{{ go_packages }}"

- name: Download Rust binaries
  ansible.builtin.shell: cargo install --root /usr/local {{ item }}
  loop: "{{ rust_packages }}"

- name: Download Linux binaries
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.name }}"
    mode: '0755'
  loop: "{{ linux_binaries }}"

- name: Download and unarchive Linux zipped binaries
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: /usr/local/bin/
    remote_src: yes
  loop: "{{ linux_zipped_binaries }}"

- name: Download Windows binaries
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/share/windows-resources/binaries/{{ item.name }}"
    mode: '0755'
  loop: "{{ windows_binaries }}"

- name: Download and unarchive Windows zipped binaries
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: /usr/share/windows-resources/binaries/
    remote_src: yes
  loop: "{{ windows_zipped_binaries }}"
