- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 3600
    autoremove: true
    autoclean: true
    purge: true

- name: Install useful apt packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
  loop: "{{ apt_packages }}"

- name: Set timezone to Europe/Paris
  community.general.timezone:
    name: Europe/Paris

- name: Enable auditd
  ansible.builtin.systemd_service:
    name: auditd
    enabled: true
    masked: no

- name: Download hashcat rules
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/share/hashcat/rules/{{ item.name }}"
    mode: '0644'
  loop: "{{ hashcat_rules }}"
