- name: Copy i3 configuration
  ansible.builtin.copy:
    src: i3
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"

- name: Copy i3status configuration
  ansible.builtin.copy:
    src: i3status
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"

- name: Copy picom configuration
  ansible.builtin.copy:
    src: picom
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/"

- name: Ensure CRLF is not present in configuration files
  ansible.builtin.replace:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/{{ item }}"
    regexp: "\r$"
    replace: ""
  loop:
    - "i3/config"
    - "i3status/config"
    - "picom/picom.conf"
